fix: serverless app more method
midwayjs/midway pull request #1034
Opened 2021-05-08 07:18 UTC by echosoar

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2021-05-08 11:05 UTC, czy88840616 approved these changes

2021-05-08 11:05 UTC, czy88840616 commented on packages-serverless/serverless-app/src/utils.ts
> +      if (methodList.includes('any') || methodList.includes('all')) {
这里应该拿不到 any 和 all 了。

2021-05-08 11:05 UTC, czy88840616 commented on packages-serverless/serverless-app/src/utils.ts
> +      const httpTrigger = allFunc[funcName].events.find(event => {
现在重复路径会抛错，不可能出现。

2021-05-08 11:06 UTC, czy88840616 requested changes
改改?

2021-05-10 06:13 UTC, echosoar commented on packages-serverless/serverless-app/src/utils.ts
> +      const httpTrigger = allFunc[funcName].events.find(event => {
同一个方法上面没法添加多个装饰器？@Get 和 @Post 都加在一个方法上面

2021-05-11 08:27 UTC, merged